Public Class Problem45
    '////////////////////////////////////////////////////////////////////////////////////////
    'Euler Projects Problem 45:
    'Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    'Triangle 	  	T_(n)=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
    'Pentagonal 	  	P_(n)=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
    'Hexagonal 	  	H_(n)=n(2n−1) 	  	1, 6, 15, 28, 45, ...
    'It can be verified that T_(285) = P_(165) = H_(143) = 40755.
    'Find the next triangle number that is also pentagonal and hexagonal.
    '////////////////////////////////////////////////////////////////////////////////////////
    Private Sub Problem45_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        For i = 40756 To 10000000000 'starts at 1 after the number in the question, arbitrary end point
            If IsTriangle(i) = True Then
                If IsPentagonal(i) = True Then
                    If IsHexagonal(i) = True Then
                        TextBox1.Text = i 'if number tested passes all the tests, print the number and end the sub
                        Exit Sub
                    End If
                End If
            End If
        Next
    End Sub

    Function IsTriangle(ByVal n As Int64)
        Dim x As Double = Math.Sqrt((n * 8) + 1) 'calculate to see if it a triangular number. A number is triangular if the square root of (n*8) + 1 is an integer
        Dim y As Int64 = x 'create an integer variable and place the result of the above in it.

        If x = y Then 'compare integer and double to see if they are the same
            Return True 'if they are, then it is a triangular number
        Else
            Return False
        End If

    End Function

    Function IsPentagonal(ByVal n As Int64)
        Dim x As Double = (Math.Sqrt((24 * n) + 1) + 1) / 6 'a number is pentagonal if the result of √((24*n)+1) + 1 / 6 is an integer
        Dim y As Int64 = x 'create an integer variable and place the result of the above in it.

        If x = y Then 'compare the integer and double to see if they are the same
            Return True 'if they are, then it is a pentagonal number
        Else
            Return False
        End If

    End Function

    Function IsHexagonal(ByVal n As Int64)
        Dim x As Double = (Math.Sqrt((8 * n) + 1) + 1) / 4  'a number is hexagonal if the result of √((8*n)+1) + 1 / 4 is an integer
        Dim y As Int64 = x 'create an integer variable and put the double variable in it

        If x = y Then 'compare the two
            Return True 'if they are the same, n is a hexagonal number
        Else
            Return False
        End If
    End Function
End Class
